from lancedb import Schema, Field

class DistributionCenter(Schema):
    id = Field(int, primary_key=True)
    name = Field(str)
    latitude = Field(float)
    longitude = Field(float)

class InventoryItem(Schema):
    id = Field(int, primary_key=True)
    product_id = Field(int)
    created_at = Field(str)
    sold_at = Field(str)
    cost = Field(float)
    product_category = Field(str)
    product_name = Field(str)
    product_brand = Field(str)
    product_retail_price = Field(float)
    product_department = Field(str)
    product_sku = Field(str)
    product_distribution_center_id = Field(int)

class OrderItem(Schema):
    id = Field(int, primary_key=True)
    order_id = Field(int)
    user_id = Field(int)
    product_id = Field(int)
    inventory_item_id = Field(int)
    status = Field(str)
    created_at = Field(str)
    shipped_at = Field(str)
    delivered_at = Field(str)
    returned_at = Field(str)
    sale_price = Field(float)

class Order(Schema):
    order_id = Field(int, primary_key=True)
    user_id = Field(int)
    status = Field(str)
    gender = Field(str)
    created_at = Field(str)
    returned_at = Field(str)
    shipped_at = Field(str)
    delivered_at = Field(str)
    num_of_item = Field(int)

class Product(Schema):
    id = Field(int, primary_key=True)
    cost = Field(float)
    category = Field(str)
    name = Field(str)
    brand = Field(str)
    retail_price = Field(float)
    department = Field(str)
    sku = Field(str)
    distribution_center_id = Field(int)

class User(Schema):
    id = Field(int, primary_key=True)
    first_name = Field(str)
    last_name = Field(str)
    email = Field(str)
    age = Field(int)
    gender = Field(str)
    state = Field(str)
    street_address = Field(str)
    postal_code = Field(str)
    city = Field(str)
    country = Field(str)
    latitude = Field(float)
    longitude = Field(float)
    traffic_source = Field(str)
    created_at = Field(str)